### ISSUE TITLE
Query error

### ISSUE THREAD

**Issue by esadek** [FrigadeHQ/trench#15]
I am getting a `queries.queries is not iterable` client error when running the "Execute raw SQL queries" section of the quickstart.

```
> curl -i -X POST \
   -H "Authorization:Bearer private-d613be4e-di03-4b02-9058-70aa4j04ff28" \
   -H "Content-Type:application/json" \
   -d \
'{
  "query": "SELECT COUNT(*) FROM events WHERE userId = '550e8400-e29b-41d4-a716-446655440000'"
}' \
 'http://localhost:4000/queries'

HTTP/1.1 400 Bad Request
access-control-allow-origin: *
access-control-allow-credentials: true
access-control-expose-headers: Authorization
content-type: application/json; charset=utf-8
content-length: 62
Date: Sat, 02 Nov 2024 01:11:34 GMT
Connection: keep-alive
Keep-Alive: timeout=72

{"statusCode":400,"message":"queries.queries is not iterable"}
```

**Comment by christianmat** [comment]
Thanks for the sample curl call, I will take a look to reproduce. Could you share the event you inserted you’re expecting to get returned?

**Comment by esadek** [comment]
It was the event from the quickstart:

```
curl -i -X POST \
   -H "Authorization:Bearer public-d613be4e-di03-4b02-9058-70aa4j04ff28" \
   -H "Content-Type:application/json" \
   -d \
'{
  "events": [
    {
      "userId": "550e8400-e29b-41d4-a716-446655440000",
      "type": "track",
      "event": "ConnectedAccount",
      "properties": {
        "totalAccounts": 4,
        "country": "Denmark"
      }
    }]
}' \
 'http://localhost:4000/events'
```

**Comment by christianmat** [comment]
Great, thanks for sharing, I have everything needed now to resolve this issue.

**Comment by christianmat** [comment]
So the issue here is actually a documentation bug. The quickstart had the wrong syntax on the queries endpoint. Please refer to the API docs for the right syntax: https://docs.trench.dev/api-reference/queries-execute

I've updated the `README` to reflect this and added additional type check to the queries endpoint. Thanks for the report!
