### ISSUE TITLE
Transition to nestjs/logger

### ISSUE THREAD

**Issue by tuminzee** [FrigadeHQ/trench#36]
To standardize and improve logging, we should replace all console.log instances with `nestjs/logger`. It provides:

Log Levels: (`log`, `error`, `warn`, `debug`, `verbose`) for better categorization.
Environment Awareness: Adjusts log output based on `NODE_ENV`.
Future Extensibility: Enables easy integration with tools like Pino, Winston, or OTEL.

**Comment by christianmat** [comment]
Thanks -- as discussed in the community Slack, feel free to open a PR for this.

**Comment by tuminzee** [comment]
on it @christianmat
